name: Backend Build

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!client/**"
  pull_request:
    branches:
      - main
    paths:
      - "**"
      - "!client/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1

      - name: Build Go backend
        run: go build -v main.go
